config/routes.rb
Bloccit::Application.routes.draw do
 
  get "comments/new"
  devise_for :users
    resources :users, only: [:update, :show, :index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts' do
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  get 'about' => 'welcome#about'
  
  root to: 'welcome#index'
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote."}

  after_save :update_post

  def up_vote?
    value == 1
  end

  def down_vote?
    value == -1
  end

  private
  
  def update_post
    post.update_rank
  end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :load_post_and_vote

  def up_vote
    update_vote!(1)
   
    # http://apidock.com/rails/ActionController/Base/redirect_to
    redirect_to :back
  end

  def down_vote
    update_vote!(-1)

    # http://apidock.com/rails/ActionController/Base/redirect_to
    redirect_to :back
  end

  private

  def load_post_and_vote
    @post = Post.find(params[:post_id])
    @vote = @post.votes.where(user_id: current_user.id).first
  end

  def update_vote!(new_value)
    if @vote
      authorize @vote, :update?
      @vote.update_attribute(:value, new_value) 
    else
      @vote = current_user.votes.build(value: new_value, post: @post)
      authorize @vote, :create?
      @vote.save
    end
  end

end

app/views/votes/_voter.html.erb
<% if policy(Vote.new).create? %>
  <div class='pull-left vote-arrows'>
    <div>
      <%= link_to " ", 
        post_up_vote_path(post), class: "glyphicon glyphicon-chevron-up #{(current_user.voted(post) && current_user.voted(post).up_vote?) ? 'voted' : '' }", method: :create %>
    </div>
    <div>
      <strong><%= post.points %></strong>
    </div>
    <div>
      <%= link_to " ", post_down_vote_path(post), class: "glyphicon glyphicon-chevron-down #{(current_user.voted(post) && current_user.voted(post).down_vote?) ? 'voted' : '' }", method: :create %>
    </div>
  </div>
<% end %>